/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125ProblemsRouteImport } from './routes/{-$locale}/problems'
import { Route as Char123LocaleChar125PartsRouteImport } from './routes/{-$locale}/parts'
import { Route as Char123LocaleChar125ManualsRouteImport } from './routes/{-$locale}/manuals'
import { Route as Char123LocaleChar125GuidesRouteImport } from './routes/{-$locale}/guides'
import { Route as Char123LocaleChar125ForumRouteImport } from './routes/{-$locale}/forum'
import { Route as Char123LocaleChar125CompatibilityRouteImport } from './routes/{-$locale}/compatibility'
import { Route as Char123LocaleChar125CommunityRouteImport } from './routes/{-$locale}/community'
import { Route as Char123LocaleChar125ComingSoonRouteImport } from './routes/{-$locale}/coming-soon'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ProblemsRoute =
  Char123LocaleChar125ProblemsRouteImport.update({
    id: '/{-$locale}/problems',
    path: '/{-$locale}/problems',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PartsRoute =
  Char123LocaleChar125PartsRouteImport.update({
    id: '/{-$locale}/parts',
    path: '/{-$locale}/parts',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ManualsRoute =
  Char123LocaleChar125ManualsRouteImport.update({
    id: '/{-$locale}/manuals',
    path: '/{-$locale}/manuals',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125GuidesRoute =
  Char123LocaleChar125GuidesRouteImport.update({
    id: '/{-$locale}/guides',
    path: '/{-$locale}/guides',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ForumRoute =
  Char123LocaleChar125ForumRouteImport.update({
    id: '/{-$locale}/forum',
    path: '/{-$locale}/forum',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125CompatibilityRoute =
  Char123LocaleChar125CompatibilityRouteImport.update({
    id: '/{-$locale}/compatibility',
    path: '/{-$locale}/compatibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125CommunityRoute =
  Char123LocaleChar125CommunityRouteImport.update({
    id: '/{-$locale}/community',
    path: '/{-$locale}/community',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ComingSoonRoute =
  Char123LocaleChar125ComingSoonRouteImport.update({
    id: '/{-$locale}/coming-soon',
    path: '/{-$locale}/coming-soon',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/{-$locale}/about',
    path: '/{-$locale}/about',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/coming-soon': typeof Char123LocaleChar125ComingSoonRoute
  '/{-$locale}/community': typeof Char123LocaleChar125CommunityRoute
  '/{-$locale}/compatibility': typeof Char123LocaleChar125CompatibilityRoute
  '/{-$locale}/forum': typeof Char123LocaleChar125ForumRoute
  '/{-$locale}/guides': typeof Char123LocaleChar125GuidesRoute
  '/{-$locale}/manuals': typeof Char123LocaleChar125ManualsRoute
  '/{-$locale}/parts': typeof Char123LocaleChar125PartsRoute
  '/{-$locale}/problems': typeof Char123LocaleChar125ProblemsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/coming-soon': typeof Char123LocaleChar125ComingSoonRoute
  '/{-$locale}/community': typeof Char123LocaleChar125CommunityRoute
  '/{-$locale}/compatibility': typeof Char123LocaleChar125CompatibilityRoute
  '/{-$locale}/forum': typeof Char123LocaleChar125ForumRoute
  '/{-$locale}/guides': typeof Char123LocaleChar125GuidesRoute
  '/{-$locale}/manuals': typeof Char123LocaleChar125ManualsRoute
  '/{-$locale}/parts': typeof Char123LocaleChar125PartsRoute
  '/{-$locale}/problems': typeof Char123LocaleChar125ProblemsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/coming-soon': typeof Char123LocaleChar125ComingSoonRoute
  '/{-$locale}/community': typeof Char123LocaleChar125CommunityRoute
  '/{-$locale}/compatibility': typeof Char123LocaleChar125CompatibilityRoute
  '/{-$locale}/forum': typeof Char123LocaleChar125ForumRoute
  '/{-$locale}/guides': typeof Char123LocaleChar125GuidesRoute
  '/{-$locale}/manuals': typeof Char123LocaleChar125ManualsRoute
  '/{-$locale}/parts': typeof Char123LocaleChar125PartsRoute
  '/{-$locale}/problems': typeof Char123LocaleChar125ProblemsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/{-$locale}/about'
    | '/{-$locale}/coming-soon'
    | '/{-$locale}/community'
    | '/{-$locale}/compatibility'
    | '/{-$locale}/forum'
    | '/{-$locale}/guides'
    | '/{-$locale}/manuals'
    | '/{-$locale}/parts'
    | '/{-$locale}/problems'
    | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/{-$locale}/about'
    | '/{-$locale}/coming-soon'
    | '/{-$locale}/community'
    | '/{-$locale}/compatibility'
    | '/{-$locale}/forum'
    | '/{-$locale}/guides'
    | '/{-$locale}/manuals'
    | '/{-$locale}/parts'
    | '/{-$locale}/problems'
    | '/{-$locale}'
  id:
    | '__root__'
    | '/'
    | '/{-$locale}/about'
    | '/{-$locale}/coming-soon'
    | '/{-$locale}/community'
    | '/{-$locale}/compatibility'
    | '/{-$locale}/forum'
    | '/{-$locale}/guides'
    | '/{-$locale}/manuals'
    | '/{-$locale}/parts'
    | '/{-$locale}/problems'
    | '/{-$locale}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ComingSoonRoute: typeof Char123LocaleChar125ComingSoonRoute
  Char123LocaleChar125CommunityRoute: typeof Char123LocaleChar125CommunityRoute
  Char123LocaleChar125CompatibilityRoute: typeof Char123LocaleChar125CompatibilityRoute
  Char123LocaleChar125ForumRoute: typeof Char123LocaleChar125ForumRoute
  Char123LocaleChar125GuidesRoute: typeof Char123LocaleChar125GuidesRoute
  Char123LocaleChar125ManualsRoute: typeof Char123LocaleChar125ManualsRoute
  Char123LocaleChar125PartsRoute: typeof Char123LocaleChar125PartsRoute
  Char123LocaleChar125ProblemsRoute: typeof Char123LocaleChar125ProblemsRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/problems': {
      id: '/{-$locale}/problems'
      path: '/{-$locale}/problems'
      fullPath: '/{-$locale}/problems'
      preLoaderRoute: typeof Char123LocaleChar125ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/parts': {
      id: '/{-$locale}/parts'
      path: '/{-$locale}/parts'
      fullPath: '/{-$locale}/parts'
      preLoaderRoute: typeof Char123LocaleChar125PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/manuals': {
      id: '/{-$locale}/manuals'
      path: '/{-$locale}/manuals'
      fullPath: '/{-$locale}/manuals'
      preLoaderRoute: typeof Char123LocaleChar125ManualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/guides': {
      id: '/{-$locale}/guides'
      path: '/{-$locale}/guides'
      fullPath: '/{-$locale}/guides'
      preLoaderRoute: typeof Char123LocaleChar125GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/forum': {
      id: '/{-$locale}/forum'
      path: '/{-$locale}/forum'
      fullPath: '/{-$locale}/forum'
      preLoaderRoute: typeof Char123LocaleChar125ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/compatibility': {
      id: '/{-$locale}/compatibility'
      path: '/{-$locale}/compatibility'
      fullPath: '/{-$locale}/compatibility'
      preLoaderRoute: typeof Char123LocaleChar125CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/community': {
      id: '/{-$locale}/community'
      path: '/{-$locale}/community'
      fullPath: '/{-$locale}/community'
      preLoaderRoute: typeof Char123LocaleChar125CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/coming-soon': {
      id: '/{-$locale}/coming-soon'
      path: '/{-$locale}/coming-soon'
      fullPath: '/{-$locale}/coming-soon'
      preLoaderRoute: typeof Char123LocaleChar125ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/{-$locale}/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125ComingSoonRoute: Char123LocaleChar125ComingSoonRoute,
  Char123LocaleChar125CommunityRoute: Char123LocaleChar125CommunityRoute,
  Char123LocaleChar125CompatibilityRoute:
    Char123LocaleChar125CompatibilityRoute,
  Char123LocaleChar125ForumRoute: Char123LocaleChar125ForumRoute,
  Char123LocaleChar125GuidesRoute: Char123LocaleChar125GuidesRoute,
  Char123LocaleChar125ManualsRoute: Char123LocaleChar125ManualsRoute,
  Char123LocaleChar125PartsRoute: Char123LocaleChar125PartsRoute,
  Char123LocaleChar125ProblemsRoute: Char123LocaleChar125ProblemsRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
