/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as ManualsRouteImport } from './routes/manuals'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualsRoute = ManualsRouteImport.update({
  id: '/manuals',
  path: '/manuals',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/community': typeof CommunityRoute
  '/compatibility': typeof CompatibilityRoute
  '/guides': typeof GuidesRoute
  '/manuals': typeof ManualsRoute
  '/parts': typeof PartsRoute
  '/problems': typeof ProblemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/community': typeof CommunityRoute
  '/compatibility': typeof CompatibilityRoute
  '/guides': typeof GuidesRoute
  '/manuals': typeof ManualsRoute
  '/parts': typeof PartsRoute
  '/problems': typeof ProblemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/community': typeof CommunityRoute
  '/compatibility': typeof CompatibilityRoute
  '/guides': typeof GuidesRoute
  '/manuals': typeof ManualsRoute
  '/parts': typeof PartsRoute
  '/problems': typeof ProblemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coming-soon'
    | '/community'
    | '/compatibility'
    | '/guides'
    | '/manuals'
    | '/parts'
    | '/problems'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coming-soon'
    | '/community'
    | '/compatibility'
    | '/guides'
    | '/manuals'
    | '/parts'
    | '/problems'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coming-soon'
    | '/community'
    | '/compatibility'
    | '/guides'
    | '/manuals'
    | '/parts'
    | '/problems'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ComingSoonRoute: typeof ComingSoonRoute
  CommunityRoute: typeof CommunityRoute
  CompatibilityRoute: typeof CompatibilityRoute
  GuidesRoute: typeof GuidesRoute
  ManualsRoute: typeof ManualsRoute
  PartsRoute: typeof PartsRoute
  ProblemsRoute: typeof ProblemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuals': {
      id: '/manuals'
      path: '/manuals'
      fullPath: '/manuals'
      preLoaderRoute: typeof ManualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ComingSoonRoute: ComingSoonRoute,
  CommunityRoute: CommunityRoute,
  CompatibilityRoute: CompatibilityRoute,
  GuidesRoute: GuidesRoute,
  ManualsRoute: ManualsRoute,
  PartsRoute: PartsRoute,
  ProblemsRoute: ProblemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
